session_name: cargo
windows:
  - window_name: watcher
    layout: even-horizontal
    panes:
      - cargo watch -x 'clippy --features full'
      - cargo watch -x 'test --features full'
      - cargo watch -x 'doc --features full'
