[package]
name = "lewp-dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcdom = { version = "0.1", package = "markup5ever_rcdom" }
html5ever = "0.25"
langtag = "0.2"
log = "0.4"
